### ISSUE TITLE
handle properties with numeric identifiers

### ISSUE THREAD

**Issue by Tyler-IN** [HavenDV/OpenApiGenerator#12]
![image](https://github.com/HavenDV/OpenApiGenerator/assets/33945568/1a04676c-6229-466d-8940-241c79c93705)

```cs
        /// <summary>
        /// 
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("300x200")]
        public string? 300x200 { get; set; }
```

**Comment by HavenDV** [comment]
Hi. Can you provide OpenAPI spec? I will test it and fix all issues, or maybe even add this to test cases and ensure it compiling without any problems.

**Comment by HavenDV** [comment]
There is already a fix for such cases for enums, so I just applied it for properties. Should be on NuGet within 5 minutes

**Comment by Tyler-IN** [comment]
If you have a fix already, that'll be great

**Comment by Tyler-IN** [comment]
I will close this for you as soon as I pull and test my code base.

The properties are thumbnail image sizes.

If there are any unrelated issues, I'll also close this ticket and make a new one to address those, but I think this is all that is needed. 👍

**Comment by HavenDV** [comment]
Everything is fine, I think your fix is ​​better and covers a wider range of options, where properties begin not only with numbers, but in general all invalid beginnings of properties
But for testing, I would prefer to create some new openapi spec based on petstore in order to define special cases like this. I'll put your test data in this OpenAPI spec
Thanks for testing and I'll be happy to fix any other problems if they arise.
Now my main priority for the coming days is support for AnyOf/OneOf, where special types/Json Converters will be generated in such cases. This is needed to support the OpenAI specification
